<?php

/**
 * @file
 * Contains mystocks.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function mystocks_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the mystocks module.
    case 'help.page.mystocks':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('stocks that are going to be selected to be purchased') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function mystocks_theme() {
  $theme = [];

  return $theme;
}
